project:
  type: website
  render:
    - "!scratch/"
    - "vignettes/*.ipynb"
    - "icu_discharges/*.ipynb"
    - "icu_discharges/*.qmd"
    - "*.qmd"
    - "*.md"
    - "*.ipynb"

execute: 
  freeze: auto

website:
  title: "HyStakes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: vignettes/vignettes.qmd
        text: Vignettes
      - about.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "ICU discharges"
        contents:
          - icu_discharges/bayes-for-discharge.qmd
  repo-url: https://github.com/hylode/hystakes
  repo-actions: [edit, issue]
  repo-subdir: hystakes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


