project:
  type: website
  render:
    - "!scratch/"
    - "vignettes/*.ipynb"
    - "vignettes/*.qmd"
    - "tutorial/*.ipynb"
    - "tutorial/*.qmd"
    - "*.qmd"
    - "*.md"
    - "*.ipynb"

execute: 
  freeze: auto

website:
  title: "HyStakes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: vignettes/vignettes.qmd
        text: Vignettes
      - about.qmd
    right:
      - icon: github
        href: https://github.com/HYLODE/HyStakes
        aria-label: GitHub
  sidebar:
    style: "docked"
    contents:
      - section: "ICU discharges"
        contents:
          - tutorial/bayes-for-discharge.qmd
  repo-url: https://github.com/hylode/hystakes
  repo-actions: [edit, issue]
  repo-subdir: hystakes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


