---
title: "Predicting discharge using Bayesian statistics"
format:
  html:
    code-fold: true
jupyter: python3
---

Our goal is to develop a Bayesian model to predict a patient's probability of being discharged in the next 24 hours. 

Note that, for now in this first attempt, I'm assuming you have some prior knowledge of Bayesian statistics. 

Here are three initial steps I think we need to do: 

 1. Decide on our "prior" probability and express it as a distribution 
 2. Identify some data we can use for the "likelihood". This can be synthetic to start with
 3. Develop a posterior distribution from the prior and likelihood. 

1. Prior probability

We expressed the probability of discharge as \theta.  Our prior belief about \theta could be that it follows a beta distribution which is expressed as follows:

$$
\theta = Beta(\alpha,\beta)
$$ {#eq-prior}

Let's say we know that 5% of patients are discharged on any given day. Therefore we'd like the expected value of our Beta distribution to be at 0.05. The expected value of a Beta distribution is given by

$$
Exp(\theta) = \frac{\alpha}{\alpha + \beta}
$$

So if we set \alpha to be 1 and \beta to be 19, we'll get an expected value of 0.05

$$
\theta = Beta(1,19)
$$ {#eq-prior2}

Plotting this: 

```{python}
#| label: prior
#| fig-cap: "Prior distribution"

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta


a, b = 2, 38
fig, ax = plt.subplots(1, 1)

x = np.linspace(beta.ppf(0.01, a, b),
                beta.ppf(0.99, a, b), 100)
ax.plot(x, beta.pdf(x, a, b),
       'r-', lw=5, alpha=0.6, label='beta pdf')

plt.show()
```